variable "name" {}

variable "vpc_id" {
        description = "id of the root vpc"
}

variable "subnet_name"  {
	description = "Subnet name hosting redis generated by VPC module"
}

variable "node_type" {
	description = "size of the redis nodes"
}

variable "replica_count" {
	description = "number of read replica node per cluster"
}

variable "group_count" {
	description = "number of groups, better one per az"
}

variable "sg" {
	description = "ID of the security group to use"
}


